export const categoryOptions = [
					{ label: "Main", value: "main" },
					{ label: "Side", value: "side" },
					{ label: "Veg", value: "veg" },
					{ label: "Salad", value: "salad" },
					{ label: "Soup", value: "soup" },
				];

export const unitOptions = [
					{
						value: "kg",
						label: "Kilogram",
					},
					{
						value: "gr",
						label: "Gram",
					},
					{
						value: "li",
						label: "Liter",
					},
					{
						value: "ml",
						label: "Milliliter",
					},
					{
						value: "tblsp",
						label: "Tablespoon",
					},
					{
						value: "tsp",
						label: "Teaspoon",
					},
					{
						value: "cup",
						label: "Cup",
					},
					{
						value: "pinch",
						label: "Pinch",
					},
					{
						value: "item",
						label: "Item",
					},
				];

// const recipeingredients = [
// 	{
// 		_id: "667419fd2e14694d8f640a27",
// 		category: "Vegetable",
// 		name: "Carrots",
// 		description: "Large carrots",
// 		unit: "kilogram",
// 		volume: 1,
// 		price: 30.45,
// 		__v: 0,
// 		id: "667419fd2e14694d8f640a27",
// 	},
// 	{
// 		_id: "66757cbe68ee8db4fdf82bef",
// 		category: "Oil",
// 		name: "Olive Oil",
// 		description: "virgin",
// 		unit: "l",
// 		volume: 1,
// 		price: 270.5,
// 		__v: 0,
// 		id: "66757cbe68ee8db4fdf82bef",
// 	},
// 	{
// 		_id: "667583d168ee8db4fdf82bf3",
// 		category: "Canned",
// 		name: "Beans",
// 		description: "Kidney",
// 		unit: "g",
// 		volume: 350,
// 		price: 22.8,
// 		__v: 0,
// 		id: "667583d168ee8db4fdf82bf3",
// 	},
// 	{
// 		_id: "66758b7768ee8db4fdf82bfb",
// 		category: "Vegetable",
// 		name: "Cabbage",
// 		description: "Green",
// 		unit: "kg",
// 		volume: 1,
// 		price: 30.98,
// 		__v: 0,
// 		id: "66758b7768ee8db4fdf82bfb",
// 	},
// 	{
// 		_id: "66758ca768ee8db4fdf82c01",
// 		category: "Herbs & Spice",
// 		name: "Paprika",
// 		description: "Smoked",
// 		unit: "g",
// 		volume: 250,
// 		price: 40,
// 		__v: 1,
// 		id: "66758ca768ee8db4fdf82c01",
// 	},
// 	{
// 		_id: "667590d768ee8db4fdf82c05",
// 		category: "Meat",
// 		name: "Chicken",
// 		description: "Thighs",
// 		unit: "kg",
// 		volume: 1,
// 		price: 99,
// 		__v: 0,
// 		id: "667590d768ee8db4fdf82c05",
// 	},
// 	{
// 		_id: "667871841d93dc011d488906",
// 		category: "Fish",
// 		name: "Hake",
// 		description: "Hake fillet",
// 		unit: "kilogram",
// 		volume: 1,
// 		price: 120.75,
// 		__v: 0,
// 		id: "667871841d93dc011d488906",
// 	},
// ];
