export const categories = [
					{ label: "Beef", value: "beef" },
					{ label: "Pork", value: "pork" },
					{ label: "Lamb", value: "lamb" },
					{ label: "Poultry", value: "poultry" },
					{ label: "Seafood", value: "seafood" },
					{ label: "Vegetable", value: "vegetable" },
					{ label: "Fruit", value: "fruit" },
					{ label: "Dairy", value: "dairy" },
					{ label: "Grain", value: "grain" },
					{ label: "Pasta", value: "pasta" },
					{ label: "Herbs/Spice", value: "herbsspice" },
					{ label: "Oil", value: "oil" },
					{ label: "Sauce", value: "sauce" },
					{ label: "Canned", value: "canned" },
					{ label: "Dried", value: "dried" },
					{ label: "Flour", value: "flour" },
					{ label: "Other", value: "other" },
				];
